# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IM.Other.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IM.Other.proto',
  package='IM.Other',
  serialized_pb=_b('\n\x0eIM.Other.proto\x12\x08IM.Other\"\r\n\x0bIMHeartBeat\" \n\rIMKickUserReq\x12\x0f\n\x07user_id\x18\x01 \x02(\r\"6\n\x0eIMKickUserResp\x12\x0f\n\x07user_id\x18\x01 \x02(\r\x12\x13\n\x0breturn_code\x18\x02 \x02(\rB\x1b\n\x17\x63om.mogujie.tt.protobufH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMHEARTBEAT = _descriptor.Descriptor(
  name='IMHeartBeat',
  full_name='IM.Other.IMHeartBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=41,
)


_IMKICKUSERREQ = _descriptor.Descriptor(
  name='IMKickUserReq',
  full_name='IM.Other.IMKickUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='IM.Other.IMKickUserReq.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=75,
)


_IMKICKUSERRESP = _descriptor.Descriptor(
  name='IMKickUserResp',
  full_name='IM.Other.IMKickUserResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='IM.Other.IMKickUserResp.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='return_code', full_name='IM.Other.IMKickUserResp.return_code', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['IMHeartBeat'] = _IMHEARTBEAT
DESCRIPTOR.message_types_by_name['IMKickUserReq'] = _IMKICKUSERREQ
DESCRIPTOR.message_types_by_name['IMKickUserResp'] = _IMKICKUSERRESP

IMHeartBeat = _reflection.GeneratedProtocolMessageType('IMHeartBeat', (_message.Message,), dict(
  DESCRIPTOR = _IMHEARTBEAT,
  __module__ = 'IM.Other_pb2'
  # @@protoc_insertion_point(class_scope:IM.Other.IMHeartBeat)
  ))
_sym_db.RegisterMessage(IMHeartBeat)

IMKickUserReq = _reflection.GeneratedProtocolMessageType('IMKickUserReq', (_message.Message,), dict(
  DESCRIPTOR = _IMKICKUSERREQ,
  __module__ = 'IM.Other_pb2'
  # @@protoc_insertion_point(class_scope:IM.Other.IMKickUserReq)
  ))
_sym_db.RegisterMessage(IMKickUserReq)

IMKickUserResp = _reflection.GeneratedProtocolMessageType('IMKickUserResp', (_message.Message,), dict(
  DESCRIPTOR = _IMKICKUSERRESP,
  __module__ = 'IM.Other_pb2'
  # @@protoc_insertion_point(class_scope:IM.Other.IMKickUserResp)
  ))
_sym_db.RegisterMessage(IMKickUserResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027com.mogujie.tt.protobufH\003'))
# @@protoc_insertion_point(module_scope)
